### ISSUE TITLE
Quests with FTB Teams

### ISSUE THREAD

**Issue by DjJanyXx** [Electrofried/ModColonies#1]
Hello,

On Modcolonies 0.5.5, i have made my server.
With my wife we create New ftb teams and when she joins team, then not one quest cant complete, not even the first with tick. 

I was using /ftbteams party create name
She /ftbteams party join name

**Comment by Electrofried** [comment]
This is a known issue with FTB  teams/quests, nothing I can do about it till they update their mods.
For now you will need both of you to leave the team in order to do the quests.
You can unclaim any area and simply disable mob griefing if it is an issue.

**Comment by DjJanyXx** [comment]
Thanks!

**Comment by Electrofried** [comment]
Will leave this open till the mod is updated to resolve the issue for visibility.

**Comment by Electrofried** [comment]
This is now resolved in the latest version 0.6.0
You will however need to log off/back on for quests to work.
Also when you join a team, you quest data resets as it becomes the "Team" quest data. It may be possible to manually copy your existing data over but that is unsupported.
