### ISSUE TITLE
Jungle Blueprints review if possible (lot of work)

### ISSUE THREAD

**Issue by XxN4BxX** [Electrofried/ModColonies#10]
if possible, removing the low hanging vines on the jungle blueprints, just 1 spot of vines should be enough, i lost 5 colonists and it took me over 17h to build an university, and it just ended because i babysitted the builde for 3h strait so he could build it

problem is, whenever a builder dies, the next one checks if whats currently builded corresponds with the blueprint, if it doesnt it will take it doen, not i had to see that 4x for about 1h because he was trimming vines before resuming building, so just taking down the vines and leaving the most top ones. and this one was just lvl 1 uni, i lost 2 builders when building a farm as well, 

already posted on their discord about this problem and unfortunately cannot do it myself because my laptop cannot handle an internal server running along with the game

link about the way to make new blueprint work on the hut's down below:
https://wiki.minecolonies.ldtteam.com/source/tutorials/schematics#how-to-override-some-built-in-schematics

**Comment by Electrofried** [comment]
This is an issue with the minecolonies mod. please report it on[ their github](https://github.com/ldtteam/minecolonies/issues). Not a pack issue.
