### ISSUE TITLE
Sharpening kits with broken tools

### ISSUE THREAD

**Issue by XxN4BxX** [Electrofried/ModColonies#11]
i used this in the past in another pack, i dont know if this was a feature implemented by the pack author or not but on early versions it was possible

teach recipe to use a specific broken tool and repair it with sharpening kits

**Comment by Electrofried** [comment]
Not a pack issue or something I can resolve. Try checking if it is an already [requested feature here](https://github.com/ldtteam/minecolonies-features/issues) and if not make a feature request.
