### ISSUE TITLE
Trapped Chests are somewhat awkward to craft

### ISSUE THREAD

**Issue by wrincewind** [Electrofried/ModColonies#16]
you can't create a vanilla trapped chest from a vanilla chest - you have to make a Quark Chest of any variety (e.g. oak), add a tripwire hook to make it a trapped chest, then convert that to a vanilla chest. Could we get this recipe added back into the game, please? (e.g. vanilla chest + tripwire hook = trapped chest)

**Comment by Electrofried** [comment]
implemented in dev
