### ISSUE TITLE
Netherite Furnace cannot output into Storage Drawers

### ISSUE THREAD

**Issue by wrincewind** [Electrofried/ModColonies#19]
I'm trying to smelt compressed cobblestone into stone using a netherite furnace (powered by a wireless heat reciever, if that's relevant) 

the furnace will happily accept compressed stone from a compating storage drawer, but it will not output into a storage drawer. I've tried putting the drawer on all sides, tried both compacting and regular drawers, tried stocking the drawer with compacted stone, but nothing works. 

the furnace outputs into a vanilla chest as expected.

**Comment by Electrofried** [comment]
This is a mod issue, report to the furnace devs and let them sort it out. When they patch it, I will update the mod.
