### ISSUE TITLE
Can't Make Compost

### ISSUE THREAD

**Issue by z64555** [Electrofried/ModColonies#21]
Modpack version 0.10.0

Can't make compost in either the minecolonies barrel nor can the Compost worker do so.  Broke/replaced the barrels, tried manually, nothing.  Recipe does not show up in JEI either so it may be a missing recipe.

**Comment by Electrofried** [comment]
Is mod issue, reported here:  ldtteam/minecolonies#7231

**Comment by Electrofried** [comment]
fixed in 0.10.3
