### ISSUE TITLE
insuficient redstone production, amounts are to low in TD

### ISSUE THREAD

**Issue by XxN4BxX** [Electrofried/ModColonies#26]
currently im having issues with redstone in many ways, wither to use in world or to make, guess it, netherack

redstone production needs a review, I'm getting about 30 redstone per hour that means 30 netherbricks (ingots) that amounts to 7 and 1/2 nether bricks (blocks), how are we supposed to get more, currently I'm getting it from 1 sifter and mine, redstone ore is being broken using fortune 3

thx

**Comment by Electrofried** [comment]
There are other methods to increase the amount of redstone from ore, you can sift for redstone, and you do not need redstone to make netherrack.
