### ISSUE TITLE
TD lock 

### ISSUE THREAD

**Issue by XxN4BxX** [Electrofried/ModColonies#30]
most buildings need prismarine at t4/t5 and there is no way of getting them from sifter since its a T5 building that is needed for that

either guardian spawn egg to setup with spawner or there must be an alternative recipe for it

**Comment by Electrofried** [comment]
Or, you could read the quests that specifically tell you the fisher can get it at lvl 3.

**Comment by XxN4BxX** [comment]
sry was relying on JEI, since it doesnt say there i though it wasnt feasible otherwise
