### ISSUE TITLE
Cannot research coke brick in university, because cannot make block of charcoal (Quark)

### ISSUE THREAD

**Issue by jjjworley** [Electrofried/ModColonies#32]
Can only make Mekanism's charcoal block, and university will not accept it. Left clicking on block of charcoal in jei does nothing, so cannot make the block. Tried to give mechanic the recipe, but he received Mekanism's recipe for charcoal block.

**Comment by Electrofried** [comment]
Make sure you are running the latest version of the pack. This issue was resolved several patches ago.

**Comment by jjjworley** [comment]
Ok. Thank you. I totally love this pack. I usually make my own packs, but this is very challenging and I have thoroughly enjoyed it!
