### ISSUE TITLE
Inventory sort buttons get in the way of crafting grid on Tinker's Crafting Station

### ISSUE THREAD

**Issue by z64555** [Electrofried/ModColonies#6]
See pic.  I'm not sure which mod adds the buttons or if there's anything that can be done pack-side.

![2021-06-05_19 12 23](https://user-images.githubusercontent.com/5084344/120908678-413b4580-c632-11eb-9565-3f69dd9a9bf8.png)

**Comment by Electrofried** [comment]
Already reported to mod dev here:
blay09/CraftingTweaks#151

Not something I can fix.

**Comment by z64555** [comment]
Ok, on the plus side I can disable the buttons from the Quark settings, accessible from the Game Menu (Escape Menu) and clicking on the 'q' button next to 'Settings'.  The buttons are in the Management group, and are the "Inventory Transfer" and "Inventory Sorting" options.
