### ISSUE TITLE
Wood Jetpack

### ISSUE THREAD

**Issue by MrAnarchyxx** [Electrofried/ModColonies#9]
The wood Jetpack is not being made. The prerequisite has been met.  Level 1 glassblower, (even upgrade to level 3 and tried) as requested, done the research, made the ask for parts of a leather strap, wood capacitor, 2 wood thruster, TNT, and order it through the postbox. The recipe is shown under a glassblower list, but when ordered and looked at using the clipboard. It saying request postbox.

**Comment by Electrofried** [comment]
I just tested this and it works fine. Ensure your building has a worker and is set to use some type of fuel.

**Comment by Electrofried** [comment]
seems the issue is only on servers, will fix next update

**Comment by Electrofried** [comment]
actually fixed in dev

**Comment by redcatone** [comment]
Still seems like an issue on the server for 0.10.4
